// Generated by CoffeeScript 1.10.0
var background, i, j, num, p, text, the_image, x, y;

text = 'Testing!';

p = new PNGlib(200, 200, 256);

background = p.color(0, 0, 0, 0);

i = 0;

num = 200 / 10;

while (i <= num) {
  x = i * 10;
  y = Math.sin(i) * Math.sin(i) * 50 + 50;
  p.buffer[p.index(Math.floor(x), Math.floor(y - 10))] = p.color(0x00, 0x44, 0xcc);
  p.buffer[p.index(Math.floor(x), Math.floor(y))] = p.color(0xcc, 0x00, 0x44);
  p.buffer[p.index(Math.floor(x), Math.floor(y + 10))] = p.color(0x00, 0xcc, 0x44);
  i += .01;
}

i = 0;

while (i < 50) {
  j = 0;
  while (j < 50) {
    p.buffer[p.index(i + 90, j + 135)] = p.color(0xcc, 0x00, 0x44);
    p.buffer[p.index(i + 80, j + 120)] = p.color(0x00, 0x44, 0xcc);
    p.buffer[p.index(i + 100, j + 130)] = p.color(0x00, 0xcc, 0x44);
    j++;
  }
  i++;
}

the_image = '<img src="data:image/png;base64,' + p.getBase64() + '">';

$('#gab-target').html(the_image);
